#!/bin/bash

_browser=${GOPEN_BROSWER:-'xdg-open'}
debug=${GOPEN_DEBUG:-'false'}

if [[ "$debug" == 1 ]] || [[ "${debug,,}" == "true" ]]; then
  set -x
fi


get_os() {
    if uname -a | grep Darwin &>/dev/null; then
        _browser=open
    fi
}

usage() {
    echo "$0 <help|edit|pipe|merge|setci|set_repo>"
    echo "opens the weburl of pwd git in browser"
    echo "Optional:"
    echo "    edit:      opens edit page of git"
    echo "    pipe:      opens pipeline page of git"
    echo "    merge:     opens merge request of git"
    echo "    setci:     opens git ci_cd settings "
    echo "    set_repo:  opens git repository settings"
    echo "    help || ?: shows this usage"
    echo "Opts:"
    echo "    -h,--help,-? shows this usage"
    exit 1
}

if [ -n "$1" ]; then
    case $1 in
        "edit"|"pipelines"|"merge_request")
            GL_URLPREFIX="/$1"
            ;;
        "pipe"|"cicd"|"actions")
            GL_URLPREFIX="/pipelines"
            GH_URLPREFIX="/actions"
            ;;
        "merge"|"pulls"|"pull")
            GL_URLPREFIX="/merge_requests"
            GH_URLPREFIX="/pull"
            ;;
        "set_ci"|"setci")
            GL_URLPREFIX="/settings/ci_cd"
            GH_URLPREFIX="settings/actions"
            ;;
        "set_repo"|"setrepo"|"setr")
            GL_URLPREFIX="/settings/repository"
            GH_URLPREFIX="/settings"
            ;;
        "help"|"?"|"--help"|"-h"|"-?")
            usage
            ;;
        *)
            GH_URLPREFIX=""
            GL_URLPREFIX=""
            ;;
    esac
fi

get_os

if git remote &>/dev/null ; then
  git_url=$(git config --get remote.origin.url)
  if [[ "$git_url" =~ ^http* ]]; then
    _git_url="$git_url"
  else
    _git_url=${git_url#git@}
    _git_url=${_git_url/:/\/}
    _git_url="https://${_git_url}"
  fi

  _git_url=${_git_url%\.git}

  sub_url=${_git_url/*\//}
  if [ -n "$sub_url" ] && [[ "$git_url" =~ "gitlab" ]]; then
    url="${_git_url}${GL_URLPREFIX}"
  elif [ -n "$sub_url" ] && [[ "$_git_url" =~ "github" ]]; then
    url="${_git_url}${GH_URLPREFIX}"
  else
    url="${_git_url}"
  fi
else
  echo "$PWD - Don't seems to be a git"
  exit 1
fi

$_browser "$url" 2>/dev/null &
